"""
04_control_energy_bootstrap.py
================================
Estimate transcription factor control energy and bootstrapped ranking for
prioritizing candidate regulators of SCβ-cell maturation.

Corresponds to Methods: "Network control energy and transcription factor
prioritization"
  "TF-target regulatory dynamics were modelled as a linear time-invariant
   system ẋ = Ax + Bu, where A is the row-normalized adjacency matrix derived
   from the consensus GRN, B is an input matrix selecting TF nodes, and x
   represents MOFA2 consensus factor projections. Rather than computing true
   minimum control energy via the controllability Gramian, input energy was
   estimated as the squared L2 norm of each TF's predicted input when the
   system is driven along the trajectory from the mean SCβ MOFA2 factor state
   toward the mean primary β-cell MOFA2 factor state via forced response
   simulation over T = 10 time steps."

Inputs:
  TF_to_MOFA_lasso_matrix_consensus.csv
    - TF × MOFA factor LASSO coefficient matrix (B matrix)
    - Generated by scripts/06_SCENIC_networks_control_energy.R
  cells_plus_mi_consensus_grn_results.csv
    - Consensus GRN edges (TF, target, importance)
    - Generated by python/02_aggregate_consensus_grn.py
  MOFA2_consensus_factors_with_metadata.csv
    - Consensus MOFA2 factor scores per cell with cell type metadata
    - Generated by scripts/08_MOFA2.R

Outputs:
  TF_control_energy_scores_consensus.csv
    - Point estimate of control energy per TF (single run, mean cell states)
  TF_control_energy_vs_factor1_consensus.csv
    - Control energy merged with LASSO coefficient on Factor 1
  bootstrap_ranked_iterations_consensus.csv
    - Per-iteration bootstrap ranking results (100 iterations × all TFs)
  bootstrap_tf_rank_summary_consensus.csv
    - Summary: mean and SD of rank across 100 bootstrap iterations per TF

Dependencies:
  pandas, numpy, networkx, control, sklearn, tqdm

Environment:
  Conda environment: pyscenic2

Usage:
  conda activate pyscenic2
  python 04_control_energy_bootstrap.py

⚠ Methodological note on control energy:
  This script does NOT compute true minimum control energy (which would
  require computing the controllability Gramian). Instead, it computes the
  squared L2 norm of B @ delta_x, where delta_x is the difference between
  mean SCβ and mean β-cell MOFA factor states. This is equivalent to asking
  "how much total input does each TF need to apply to align with the
  target state direction?" and is used for ranking TFs by relative ease
  of control, not for estimating absolute energy in physical units.
  See Methods for full discussion of assumptions and limitations.

⚠ Note on Gramian-based minimum energy (see inline comments for full detail):
  True minimum control energy via the controllability Gramian was evaluated
  but found to be numerically unstable for this GRN (condition number ~7×10²²).
  The projection-based approach (squared L2 norm of B @ delta_x) is used
  instead. Gramian code is retained in comments for reproducibility of the
  comparison. Spearman rank correlation between the two approaches: r = 0.88
  (see check_gramian_vs_projection.py).
"""

import pandas as pd
import numpy as np
import networkx as nx
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

# Note: `from control import ss, forced_response` was used in an earlier version
# that attempted Gramian-based minimum control energy. That approach was found to
# be numerically unstable (Gramian condition number ~7×10²²) for this GRN.
# See the forced response section below for full explanation.
# The `control` package is no longer required for the current implementation.

# ── Parameters ────────────────────────────────────────────────────────────────

LASSO_MATRIX    = "TF_to_MOFA_lasso_matrix_consensus.csv"
CONSENSUS_GRN   = "cells_plus_mi_consensus_grn_results.csv"
MOFA_FACTORS    = "MOFA2_consensus_factors_with_metadata.csv"
N_BOOT          = 100     # bootstrap iterations for rank stability
BOOT_FRAC       = 0.8     # fraction of cells sampled per iteration
T_STEPS         = 100     # time steps for forced response simulation
T_MAX           = 10      # end time (T = 10 steps as in Methods)
CELLTYPE_COL    = "celltype"
CELLTYPE_SCB    = "SCβ"
CELLTYPE_BETA   = "beta"

# ═══════════════════════════════════════════════════════════════════════════════
# Part 1: Point estimate of control energy (single run, mean cell states)
# ═══════════════════════════════════════════════════════════════════════════════

# ── Load B matrix (TF → MOFA factor LASSO coefficients) ───────────────────────

# B encodes each TF's influence on MOFA latent factors
# Rows = TFs, Columns = MOFA factors
# Generated by LASSO regression of MOFA factor scores on TF AUC values
df_b = pd.read_csv(LASSO_MATRIX)
df_b = df_b.set_index("TF")
TFs = df_b.index.tolist()
factor_cols = df_b.columns.tolist()

print(f"B matrix: {len(TFs)} TFs × {len(factor_cols)} MOFA factors")

# ── Build adjacency matrix A from consensus GRN ───────────────────────────────

# Restrict GRN to TF-to-TF edges only (both endpoints must be in the B matrix)
# This defines the state transition matrix for the linear dynamical system
df_grn = pd.read_csv(CONSENSUS_GRN)
df_grn = df_grn[df_grn["TF"].isin(TFs) & df_grn["target"].isin(TFs)]

print(f"GRN edges (TF→TF only): {len(df_grn)}")

# Build directed graph from TF-TF edges
G = nx.DiGraph()
for _, row in df_grn.iterrows():
    G.add_edge(row["TF"], row["target"], weight=row["importance"])

# Retain only TFs present in both the B matrix and the GRN
TFs_in_graph = [tf for tf in TFs if tf in G.nodes]
print(f"TFs with edges in GRN: {len(TFs_in_graph)} / {len(TFs)}")

# Build adjacency matrix aligned to TFs_in_graph order
A = nx.to_numpy_array(G, nodelist=TFs_in_graph, weight="weight")

# Subset B to TFs present in GRN (same ordering as A)
B = df_b.loc[TFs_in_graph].values  # shape: n_TFs × n_factors

# Row-normalize A so max absolute value = 1
# This stabilizes the linear system and ensures the dynamics don't diverge
A = A / np.max(np.abs(A))

# ── Define target state transition ────────────────────────────────────────────

# Load MOFA2 consensus factor scores
df_mofa = pd.read_csv(MOFA_FACTORS)
mofa_factor_cols = [f for f in df_mofa.columns if f.startswith("Factor")]

# Mean factor state per cell type
x0       = df_mofa[df_mofa[CELLTYPE_COL] == CELLTYPE_SCB][mofa_factor_cols].mean().values
x_target = df_mofa[df_mofa[CELLTYPE_COL] == CELLTYPE_BETA][mofa_factor_cols].mean().values
delta_x  = x_target - x0  # direction from SCβ → β-cell in factor space

print(f"Delta_x norm (SCβ → β): {np.linalg.norm(delta_x):.4f}")

# ── Define input trajectory ───────────────────────────────────────────────────

T  = np.linspace(0, T_MAX, T_STEPS)
U  = np.tile(delta_x[:, None], T_STEPS)  # shape: n_factors × T_STEPS; constant input

# ── Forced response simulation (retained for reference, not used for energy) ──
#
# The theoretically correct approach would use the controllability Gramian W_T
# to compute minimum energy: u* = B^T W_T^{-1} (x_target - e^{AT} x0)
# This was evaluated but found to be numerically unstable for this GRN:
#   - Gramian condition number: ~7 × 10²²  (far above the ~10¹² instability threshold)
#   - The pseudoinverse solution produced erratic rankings inconsistent with
#     the biological prior (e.g. ATF3 rank 219 → 3, ZNF296 rank 2 → 170)
#   - These rank changes are almost certainly numerical artifacts, not biology
#
# The projection-based approach below (B @ U, then squared L2 norm) is used
# instead. It does not use the system dynamics (A matrix does not enter the
# energy calculation), but it is stable and produces rankings consistent with
# the influence analysis. Spearman rank correlation between the two approaches
# across all TFs was r = 0.88 (see check_gramian_vs_projection.py).
#
# The ss() and forced_response() calls below are retained so a reader can see
# what was attempted. They are commented out because their output (yout, xout)
# is not used downstream.
#
# n = len(TFs_in_graph)
# sys = ss(A, B, np.eye(n), np.zeros((n, B.shape[1])))
# X0 = np.zeros(n)
# T_out, yout, xout = forced_response(sys, T=T, U=U, X0=X0, return_x=True)

# ── Compute control energy per TF ─────────────────────────────────────────────

# Input applied by each TF across all time steps: shape (n_TFs, T_STEPS)
TF_inputs = B @ U

# Energy = squared L2 norm of the input time series per TF
# Equivalent to T_STEPS * (B @ delta_x)^2 since U is constant across time steps
# Lower energy → TF's input profile better aligns with the SCβ → β direction
energy = np.sum(TF_inputs ** 2, axis=1)

df_energy = pd.DataFrame({
    "TF": TFs_in_graph,
    "ControlEnergy": energy
}).sort_values("ControlEnergy")

df_energy.to_csv("TF_control_energy_scores_consensus.csv", index=False)
print(f"\nTop 10 TFs by lowest control energy:")
print(df_energy.head(10).to_string(index=False))

# ── Merge energy with LASSO Factor 1 coefficient ──────────────────────────────

# Factor 1 LASSO coefficient reflects each TF's contribution to the primary
# MOFA separation factor — useful for joint ranking with control energy
df_lasso = pd.read_csv(LASSO_MATRIX)
df_lasso_factor1 = df_lasso[["TF", "Factor1"]].rename(
    columns={"Factor1": "Factor1_Coef"}
)

df_combined = pd.merge(df_energy, df_lasso_factor1, on="TF", how="left")
df_combined.to_csv("TF_control_energy_vs_factor1_consensus.csv", index=False)

# ═══════════════════════════════════════════════════════════════════════════════
# Part 2: Bootstrap ranking for rank stability
# ═══════════════════════════════════════════════════════════════════════════════

# The point estimate above uses mean cell states. Here we bootstrap 80% of
# cells per iteration to assess sensitivity of TF rankings to cell sampling.
# Rankings are based on DeltaX_Impact (B @ delta_x) and CosineSimilarity
# rather than squared energy — these capture directional alignment with the
# SCβ → β trajectory.

print(f"\nRunning {N_BOOT} bootstrap iterations ({int(BOOT_FRAC*100)}% cell resampling)...")

# Reload B (now using all TFs from LASSO matrix, not just GRN-filtered subset)
df_b_boot = pd.read_csv(LASSO_MATRIX)
df_b_boot = df_b_boot.set_index("TF")
B_boot    = df_b_boot.values
TFs_boot  = df_b_boot.index.tolist()

df_factors = pd.read_csv(MOFA_FACTORS)
boot_factor_cols = [col for col in df_factors.columns if col.startswith("Factor")]

bootstrap_results = []

for i in tqdm(range(N_BOOT), desc="Bootstrapping"):
    # Resample 80% of cells per cell type (with replacement)
    # Sampling with replacement means some cells will be duplicated;
    # this is intentional for bootstrap variance estimation
    scb  = df_factors[df_factors[CELLTYPE_COL] == CELLTYPE_SCB].sample(
        frac=BOOT_FRAC, replace=True
    )
    beta = df_factors[df_factors[CELLTYPE_COL] == CELLTYPE_BETA].sample(
        frac=BOOT_FRAC, replace=True
    )

    x0_boot       = scb[boot_factor_cols].mean().values
    x_target_boot = beta[boot_factor_cols].mean().values
    delta_x_boot  = x_target_boot - x0_boot

    # How much does each TF's input profile align with the target direction?
    delta_x_impact = B_boot @ delta_x_boot  # signed projection per TF

    # Cosine similarity: directional agreement between TF input and target
    cos_sim = cosine_similarity(
        B_boot, delta_x_boot.reshape(1, -1)
    ).flatten()

    for j, tf in enumerate(TFs_boot):
        bootstrap_results.append({
            "Iteration":        i,
            "TF":               tf,
            "DeltaX_Impact":    delta_x_impact[j],
            "CosineSimilarity": cos_sim[j]
        })

df_boot = pd.DataFrame(bootstrap_results)

# ── Rank TFs within each bootstrap iteration ──────────────────────────────────

df_ranked = df_boot.groupby("Iteration").apply(
    lambda df: df.assign(
        Rank_Impact = df["DeltaX_Impact"].rank(ascending=False, method="min"),
        Rank_Cosine = df["CosineSimilarity"].rank(ascending=False, method="min")
    )
).reset_index(drop=True)

# ── Summarize rank stability across iterations ────────────────────────────────

df_rank_summary = df_ranked.groupby("TF").agg(
    Mean_Rank_Impact = ("Rank_Impact", "mean"),
    SD_Rank_Impact   = ("Rank_Impact", "std"),
    Mean_Rank_Cosine = ("Rank_Cosine", "mean"),
    SD_Rank_Cosine   = ("Rank_Cosine", "std")
).reset_index()

df_ranked.to_csv("bootstrap_ranked_iterations_consensus.csv", index=False)
df_rank_summary.to_csv("bootstrap_tf_rank_summary_consensus.csv", index=False)

print("\nTop 10 TFs by mean impact rank:")
print(
    df_rank_summary.sort_values("Mean_Rank_Impact")
    .head(10)[["TF", "Mean_Rank_Impact", "SD_Rank_Impact"]]
    .to_string(index=False)
)
print("\nDone.")
